### ISSUE TITLE
How to clear *.imageurl files on finish app?

### ISSUE THREAD

**Issue by ventskus-roman** [koush/UrlImageViewHelper#11]
Good afternoon.
I will replace that in the "files" on your accumulated cached images *.imageurl.
Is it possible to clear these files when you close the program?
I understand that if you do not, the size of the folder will continue to increase until the end disk space, right?
Sorry for bad English

**Comment by koush** [comment]
Every time the app starts, any files over 3 days old are purged. There is no explicit way to clear the cache right now. I'll need ot add that.

**Comment by ventskus-roman** [comment]
thanks

**Comment by koush** [comment]
Fixed. See the new cleanup method.
