### ISSUE TITLE
Keep showing default image, when you're trying to show something that isn't an image.

### ISSUE THREAD

**Issue by ghost** [koush/UrlImageViewHelper#12]
I'm using a GET method to get resized images from the server. If the user has an avatar this methods gives me the url of the resized image, but if the user doesn't have an avatar this method returns me an error page.
I'm thinking how I can modify your code for checking if what I'm downloading is an image or something else (like an html, php... file) to keep showing the default image if there's no image in the url, but I don't know how. I think it could be a good idea to modify it, it's not a bug or a problem but it can be helpful.

**Comment by koush** [comment]
If the image fails to decode, it will continue showing the default.
