### ISSUE TITLE
Request for Javadocs

### ISSUE THREAD

**Issue by cdep** [koush/UrlImageViewHelper#16]
Just wondering if you're open to the suggestion of adding javadoc comments to your code. It looks clear enough, but I'm sorry to say that I'm lazy, so javadocs would really help. If you don't want to write javadocs, but are open to the idea of adding some, I can add some for you eventually, for other lazy freeloaders like me. I find that clear, complete javadocs are a lot more helpful than wikis and how-to guides. Thanks for your open-source work btw.

**Comment by koush** [comment]
Ah yeah, I was just thinking about that the other day. If you wanna do it go for it, I probably won't get to it for a bit.

**Comment by koush** [comment]
Looks like you added them
