### ISSUE TITLE
multiple layouts - different layout parameters.

### ISSUE THREAD

**Issue by tlbollwitt** [koush/UrlImageViewHelper#2]
I have an app that uses the same image in multiple layouts. The ImageView has different layout parameters in each layout, i.e. margin, padding, height, width, etc.
I noticed that when navigating from a ListActivity to a "detail" activity for the selected list item that the image in the list would change based on the layout parameters in the detail activity which also displays the image.

I was able to work around this by caching the Bitmap and not the Drawable. Downside is that my default drawable needs to be an image, which is fine for my app.

Other than that your code worked like a charm!

**Comment by koush** [comment]
WHy would layout parameters be associated with the drawable? Isn't that attached to an ImageView?
