### ISSUE TITLE
UrlImageViewHelper: Using DisplayMetric.width instead of getDefaultDisplay().getWidth()

### ISSUE THREAD

**Issue by cdep** [koush/UrlImageViewHelper#20]
Since Display.getWidth() and Display.getHeight() are deprecated. I was wondering why you aren't using DisplayMetric.width and DisplayMetric.height? You've already got it saved as a static variable, mMetric.

**Comment by koush** [comment]
Oh, I'll take a look at that once I am back home. Probably just forgot that was there.

**Comment by cdep** [comment]
Apparently, `setUrlDrawable(...)` can be called while `mMetrics` is still `null`, thus throwing a `NullPointerException`.
