### ISSUE TITLE
image url with redirect won't load

### ISSUE THREAD

**Issue by MarcLandis** [koush/UrlImageViewHelper#23]
The latest change seems to have problems loading images that are redirected first. An example is http://api.twitter.com/1/users/profile_image/MarcLandis?size=original

I was able to get it working again by changing the UrlDownloader method to use an AndroidHttpClient instead of an HttpURLConnection.

**Comment by koush** [comment]
Let me take a look. The latest change was just a code cleanup/reformat. The HttpUrlConnection changes happened a few weeks ago. I may have broken redirects. Will get back to you in a bit.

**Comment by koush** [comment]
Ok, I patched the code as follows:

``` java
HttpURLConnection.setFollowRedirects(true);
urlConnection.setInstanceFollowRedirects(true);
```

And it is still not following redirects... Trying to find out if this is a HttpUrlConnection bug.

**Comment by koush** [comment]
Oh, it won't follow redirects across protocol changes I think. It's going from http to https.

**Comment by koush** [comment]
```
HttpURLConnection will follow up to five HTTP redirects.
It will follow redirects from one origin server to another.
This implementation doesn't follow redirects from HTTPS to HTTP or vice versa.
```

http://developer.android.com/reference/java/net/HttpURLConnection.html

**Comment by koush** [comment]
@MarcLandis Ok I've worked around this: https://github.com/koush/UrlImageViewHelper/commit/5d49cc92f71681aa86e2a8e41d54eea5852cb8eb
