### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by reallylongaddress** [koush/UrlImageViewHelper#24]
I'm getting a very odd, hard to reproduce error.  This occurs ONLY when the app has been uploaded to play.google.com.  Another oddity is I have multiple apps running the same codebase (exactly) and this doesn't occur in the other builds.....

Thoughts?

I/dalvikvm(13872): Could not find method com.koushikdutta.urlimageviewhelper.UrlImageViewHelper.setUrlDrawable, referenced from method com.mobileigniter.android.acr.MIViewerActivity.updateLauncherView
W/dalvikvm(13872): VFY: unable to resolve static method 1293: Lcom/koushikdutta/urlimageviewhelper/UrlImageViewHelper;.setUrlDrawable (Landroid/widget/ImageView;Ljava/lang/String;)V
D/dalvikvm(13872): VFY: replacing opcode 0x71 at 0x0020
I/webclipboard(13872): clipservice: android.sec.clipboard.ClipboardExManager@412aa830
I/System.out(13872): updateLauncherView
D/AndroidRuntime(13872): Shutting down VM
W/dalvikvm(13872): threadid=1: thread exiting with uncaught exception (group=0x40b921f8)
E/AndroidRuntime(13872): FATAL EXCEPTION: main
E/AndroidRuntime(13872): java.lang.NoClassDefFoundError: com.koushikdutta.urlimageviewhelper.UrlImageViewHelper
E/AndroidRuntime(13872):    at com.mobileigniter.android.acr.MIViewerActivity.updateLauncherView(MIViewerActivity.java:162)
E/AndroidRuntime(13872):    at com.mobileigniter.android.acr.MIViewerActivity.onStart(MIViewerActivity.java:90)
E/AndroidRuntime(13872):    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1137)
E/AndroidRuntime(13872):    at android.app.Activity.performStart(Activity.java:4475)
E/AndroidRuntime(13872):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1943)
E/AndroidRuntime(13872):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
E/AndroidRuntime(13872):    at android.app.ActivityThread.access$600(ActivityThread.java:128)
E/AndroidRuntime(13872):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
E/AndroidRuntime(13872):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13872):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(13872):    at android.app.ActivityThread.main(ActivityThread.java:4514)
E/AndroidRuntime(13872):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(13872):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(13872):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(13872):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime(13872):    at dalvik.system.NativeStart.main(Native Method)
W/A

**Comment by koush** [comment]
Are you using ProGuard maybe?

**Comment by koush** [comment]
What version/SHA of UrlImageViewHelper are you using? I recall having this problem too and fixing this. Let me know what version of Android is exhibiting the issue.

**Comment by koush** [comment]
No response for a month. Closing. Pretty sure this bug was fixed.
