### ISSUE TITLE
Use custom view with the library

### ISSUE THREAD

**Issue by rfmussa** [koush/UrlImageViewHelper#27]
Hello, I am trying to use a custom view with the the library, but I always get a ClassCast exception in the ondraw.What do I have to change?

**Comment by koush** [comment]
Use loadUrlDrawable with a callback. Or inherit your view from ImageView. Or provide the internal ImageView in your composite custom view.

**Comment by rfmussa** [comment]
Could you give me an example please? I am trying to round the corners of the lazy-loaded imageview. Thanks

**Comment by koush** [comment]
Just set a style/shape for the ImageView to do that.

**Comment by koush** [comment]
http://stackoverflow.com/questions/4464347/creating-imageview-with-round-corners
