### ISSUE TITLE
Add pom.xml and upload to Maven Central

### ISSUE THREAD

**Issue by jonasfa** [koush/UrlImageViewHelper#28]
as apklib or even jar, as it doesn't have resources

**Comment by sbuettner** [comment]
+1

**Comment by jonasfa** [comment]
@koush ?

**Comment by koush** [comment]
I've never uploaded anything to Maven Central. At first glance, it looks to be a bit of a tedious process. If someone else wants to do it and maintain the package, I don't mind. I don't use maven.

**Comment by koush** [comment]
done 
https://github.com/koush/UrlImageViewHelper/pull/52
