### ISSUE TITLE
Images change in list view

### ISSUE THREAD

**Issue by kanedavid** [koush/UrlImageViewHelper#31]
I am using this to populate ImageViews held in a ListView and it seems like the first visible ImageView will display all of the images as they are downloaded from the URL. I believe this does not happen for cached images, but if they are downloaded then it will do this cycling thing.

**Comment by koush** [comment]
Are you sure they aren't just popping in from bottom to top? ImageViews use no space when there's no image in them. That may make it look like the first one shows all the images. 

Try using a placeholder image to see if it still "occurs". My guess is no, since it will be apparent which image is showing up in which image view.

**Comment by koush** [comment]
The Google Image search sample in the library does not exhibit this behavior.

**Comment by kanedavid** [comment]
I was using this by calling: 

```
UrlImageViewHelper.setUrlDrawable(imageview, imgurl);
```

And it was definitely exhibiting the behavior where the incorrect image would be loaded into an ImageView. I switched to providing a default image, however, and it is now working properly. It seems odd to me that it would work correctly with a default image provided, but not without one. Whatever, it works now so I am happy. Thank you for your suggestion.

**Comment by koush** [comment]
I'm 99% sure that it is just the perception of the first imageview loading all the images. It just happens that the image views are empty/stacked in a list view. So as they pop in above each other, it only looks like the first one is changing. I confirmed this behavior by removing the placeholder from the sample, and adding some logging to track the imageview population. I see the behavior you are describing, but it is entirely expected with how the android layout system works. It's just an incorrect visual interpretation of what is happening.

But, if you have a sample that I could use to reproduce this problem, I'd be happy to take a look.
