### ISSUE TITLE
Force Image Update

### ISSUE THREAD

**Issue by Fleisch** [koush/UrlImageViewHelper#33]
Is there anyway to force a image to update?

First time this image loads it is cached for 3 days which is fine. But if some condition happens i want to force it to update even if its cached. Is this currently possible?

Thank you

**Comment by koush** [comment]
Just call loadUrlDrawable or setIUrlDrawable with a cache duration of 0.

**Comment by Fleisch** [comment]
So if i first run
UrlImageViewHelper.setUrlDrawable(imageView, "http://example.com/image.png", null, THREE_DAYS);

Then minutes later run
UrlImageViewHelper.setUrlDrawable(imageView, "http://example.com/image.png", null, 0);

It will visit the URL to retrieve photo again despite of it being cached? Because i tried that before posting the issue and it didn't seem to work.

**Comment by koush** [comment]
@Fleisch Oh, I understand the problem now. You are refreshing within the same application session/run.

**Comment by Fleisch** [comment]
Yes sir.

I can confirm the image on the server is changing but the application still thinks its the same image because of caching. So was looking for a way to say "even if this is cached, go to the URL and get it again anyway"

Is this currently possible? Thanks!

**Comment by koush** [comment]
Yeah, I can fix this. It's a bit sticky due to how ZombieDrawables work. I'll need to do a bit of testing on this fix before I can push it up for the rest of the world.

**Comment by koush** [comment]
Fixed with https://github.com/koush/UrlImageViewHelper/commit/e8e7d11251dc119de54bb93825e1eb8df1ad0018

**Comment by koush** [comment]
Note that this will _not_ automatically refresh all the ImageViews that are using images from that url.
Every ImageView that needs to be refreshed with the new image needs to have setUrlDrawable called on it.
