### ISSUE TITLE
Avoid shrinking

### ISSUE THREAD

**Issue by Freezzz** [koush/UrlImageViewHelper#34]
First of all thanks for a great lib! It would be nice to have a flag to avoid shrinking/resampling of the downloaded image.

**Comment by koush** [comment]
Agreed. I think that shrinking is a good default behavior to avoid large memory allocations by lazy usage of the library. A flag to disable that would be appropriate.
I'll add that sometime soon.

**Comment by koush** [comment]
Fixed with https://github.com/koush/UrlImageViewHelper/commit/1697029c39c34e92086af7b3f3431f4e7512d681
