### ISSUE TITLE
'content://' uri support

### ISSUE THREAD

**Issue by EaseTheWorld** [koush/UrlImageViewHelper#35]
Thank you for developing UrlImageViewHelper.

I want to use UrlImageViewHelper for local image (MediaStore.Images.Thumbnails)
but it doesn't seem to support content:// type uri except ContactsContract.Contacts.CONTENT_URI.

I modified UrlImageViewHelper - mDefaultDownloader - doInBackground like below

if (url.startsWith(ContentResolver.SCHEME_CONTENT)) {
    final ContentResolver cr = context.getContentResolver();
    if (url.startsWith(ContactsContract.Contacts.CONTENT_URI.toString())) {
        is = ContactsContract.Contacts.openContactPhotoInputStream(cr, Uri.parse(url));
    } else {
        is = cr.openInputStream(Uri.parse(url));
    }
}

and it works as expected.

Is there any particular reason for not supporting this feature?
(memory, file i/o or something)

If this works (or at least for MediaStore.XXX), it would save me some time.

**Comment by koush** [comment]
That's a neat feature! Feel free to submit a pull request.

I never implemented it because I never needed it.
