### ISSUE TITLE
Option for disabling disk cache?

### ISSUE THREAD

**Issue by EaseTheWorld** [koush/UrlImageViewHelper#39]
I'm not sure there is option for disabling disk cache and I just couldn't found it.

If I use content:// type url, all data are already in the disk so I don't want them to be internally cached for saving space and consistency sake.

**Comment by koush** [comment]
Oh, good point. I'll fix that.

**Comment by EaseTheWorld** [comment]
I modified UrlImageViewHelper.java to disable disk cache for content scheme.
Pull Request 6b7efdb. Please check this.

**Comment by koush** [comment]
Oh nice, thanks. Will take a look.

**Comment by EaseTheWorld** [comment]
If you think content scheme url always disable disk cache (well, I do),
I could make the code a bit clearer.
For example, move all content-scheme-related code from download() to loadDrawableFromUrl(),
 and just call loader.run() in download().

**Comment by koush** [comment]
Fixed, content urls are no longer cached.
