### ISSUE TITLE
fixed: can't cache using service context

### ISSUE THREAD

**Issue by ericlw** [koush/UrlImageViewHelper#40]
Hello, I am doing an network call in a thread in a service, the response contains urls which I would like to cache. UrlImageViewHelper.loadUrlDrawable(context, "http://example.com/image.png");  requires an Activity context to get access to some bitmap controls, but my service does not have an activity context.

How can I cache here?

EDIT:
I changed prepareResources() to this, your code commented out
//final Activity act = (Activity)context;
        //act.getWindowManager().getDefaultDisplay().getMetrics(mMetrics);
        ((WindowManager) context.getSystemService(Context.WINDOW_SERVICE))
        .getDefaultDisplay().getMetrics(mMetrics);

**Comment by koush** [comment]
Looks good, mind sending a pull request?

**Comment by ericlw** [comment]
sure, how do I do that here?
