### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by travis154** [koush/UrlImageViewHelper#41]
I have this situation where I need to load many images. But too many concurrent threads doesn't work. Is there any solution for this?

**Comment by koush** [comment]
Only load the image when it is needed to be visible.

Ie, if it's in a list adapter, call the UrlImageViewHelper.setUrlDrawable in the getView.

**Comment by koush** [comment]
Or use the Android Async project https://github.com/koush/AndroidAsync and this code in your Application startup:

``` java

        final Handler handler = new Handler();
        UrlImageViewHelper.useDownloader(new UrlDownloader() {
            @Override
            public void download(final Context context, final String url, final String filename, final Runnable loader, final Runnable completion) {
                AsyncHttpClient.execute(url, new HttpConnectCallback() {
                    @Override
                    public void onConnectCompleted(Exception ex, AsyncHttpResponse response) {
                        if (ex != null) {
                            ex.printStackTrace();
                            handler.post(completion);
                            return;
                        }
                        try {
                            final OutputStreamDataCallback o = new OutputStreamDataCallback(new FileOutputStream(filename));
                            response.setDataCallback(o);
                            response.setCompletedCallback(new CompletedCallback() {
                                @Override
                                public void onCompleted(Exception ex) {
                                    if (ex != null) {
                                        ex.printStackTrace();
                                        handler.post(completion);
                                        return;
                                    }
                                    o.close();
                                    loader.run();
                                    handler.post(completion);
                                }
                            });
                        }
                        catch (Exception e) {
                            e.printStackTrace();
                            handler.post(completion);
                        }
                    }
                });
            }
        });
```

**Comment by manishkumar** [comment]
It still crashes for me, even after calling UrlImageViewHelper.setUrlDrawable in the getView.

**Comment by manijshrestha** [comment]
@manishkumar023 can you post your stacktrace?

**Comment by manishkumar** [comment]
01-09 21:46:43.559: E/AndroidRuntime(30565): FATAL EXCEPTION: main
01-09 21:46:43.559: E/AndroidRuntime(30565): Process: com.kohapp.android, PID: 30565
01-09 21:46:43.559: E/AndroidRuntime(30565): java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@427d1760 rejected from java.util.concurrent.ThreadPoolExecutor@425b34b0[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 15]
01-09 21:46:43.559: E/AndroidRuntime(30565):    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:590)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper.executeTaskHoneycomb(UrlImageViewHelper.java:805)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper.executeTask(UrlImageViewHelper.java:799)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.koushikdutta.urlimageviewhelper.HttpUrlDownloader.download(HttpUrlDownloader.java:76)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper.setUrlDrawable(UrlImageViewHelper.java:669)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper.setUrlDrawable(UrlImageViewHelper.java:237)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.koushikdutta.urlimageviewhelper.UrlImageViewHelper.setUrlDrawable(UrlImageViewHelper.java:145)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.kohapp.android.activities.FriendListFragment$MyListAdapter.getView(FriendListFragment.java:245)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.widget.AbsListView.obtainView(AbsListView.java:2240)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.widget.ListView.makeAndAddView(ListView.java:1790)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.widget.ListView.fillDown(ListView.java:691)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.widget.ListView.fillGap(ListView.java:655)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5136)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4247)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.view.Choreographer.doFrame(Choreographer.java:543)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.os.Handler.handleCallback(Handler.java:733)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.os.Handler.dispatchMessage(Handler.java:95)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.os.Looper.loop(Looper.java:136)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at android.app.ActivityThread.main(ActivityThread.java:5017)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at java.lang.reflect.Method.invokeNative(Native Method)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at java.lang.reflect.Method.invoke(Method.java:515)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
01-09 21:46:43.559: E/AndroidRuntime(30565):    at dalvik.system.NativeStart.main(Native Method)

**Comment by manijshrestha** [comment]
You might want to take a look at: http://stackoverflow.com/questions/12074985/java-util-concurrent-rejectedexecutionexception-in-async-task-android

As per the trace: 
"Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 15"

Max task it can take is 128 anything more will result in "RejectedExecutionException". You should look to see if you really need to load up more than few at a time.

Hope this helps.

**Comment by manishkumar** [comment]
Thanks for the link. 

I use the lib for loading facebook friends images in a list view and the crash happens when I frantically scroll down the list.

**Comment by manijshrestha** [comment]
yep that makes sense, you might want to check your List Adapter class and see if you can do anything different there. Do post a solution  so others with similar issues can get some useful info.

**Comment by mlakhia** [comment]
Currently looking for a solution to this exact problem. I'll post back here if I find anything :)

**Comment by koush** [comment]
This project is not seeing any active development, as I've deprecated it in favor of ion.
Ion will automatically cancel unnecessary decodes (imageviews going of screen/recycled), for example. It also uses a single reactor thread, so it can handle more concurrent downloads.

https://github.com/koush/ion

**Comment by mlakhia** [comment]
Awesome. Will be switching to Ion. Thanks!
