### ISSUE TITLE
Assertion in UrlImageViewHelper

### ISSUE THREAD

**Issue by MRyan-** [koush/UrlImageViewHelper#43]
I am working on an application that requires the rapid manipulation of alot of images, and they are going into a list view where I am recycling the views in the adapter. However, I am having instances an assertion in setUrlDrawable(Context,ImageView,String,Drawable) on line 497. I just cloned the repo today.

Other than that, the library seems to be holding up rather well.

**Comment by koush** [comment]
What type of manipulation are you doing?
You've somehow managed to get a drawable into a both "live" (referenced) and "dead" (not referenced, but not destroyed yet) state. That should be impossible, which is why I placed that assert.

**Comment by koush** [comment]
A small repro of the issue would be helpful. Are you using "getImmediateMutableDrawable" by chance? That is fairly new and may be the cause of the issue.

**Comment by MRyan-** [comment]
No, i am just using UrlImageViewHelper.setUrlDrawable

**Comment by koush** [comment]
Any chance you can share the project? I'll keep it private. I'd be happy to debug the issue.

**Comment by koush** [comment]
Same bug as https://github.com/koush/UrlImageViewHelper/issues/45

**Comment by MRyan-** [comment]
If I could, I would happily share the project. Unfortunately, I can not. I
can assure you that I am simply using setUrlDrawable as normal. If it
helps, there are scenarios where the function is called many times due to
instances where the list view is flung. We have since worked to reduce the
number of calls, but it is still not a very good thing to happen.

**Comment by koush** [comment]
Well, I've commented the assert out, since the assertion is basically benign.
