### ISSUE TITLE
junit.framework.assertionfailederror

### ISSUE THREAD

**Issue by ericlw** [koush/UrlImageViewHelper#45]
I am using thumbnails in a listview, this listview is in a viewpager. The thumbnails are already cached with urlimageviewhelper (or it may still be retrieving them). The thumbnails are loaded within the listview adapter using UrlImageViewHelper.setUrlDrawable(... , ... )

The crash if it happens points to a piece of UrlImageViewHelper drawable code. line 436 Assert.assertTrue(!mAllCache.contains(zd)); , junit.framework.assertionfailederror

Now, the listview will be rendering views for itself, as well as the viewpager rendering the left and right views (containing listviews caching). My Listviews also use a "viewholder" .So this would seem like a demanding process yes

Do I need to catch the assertionfailederror or something? I never saw this before until I made this imageview rendering monstrosity (listviews in viewpager)

**Comment by koush** [comment]
Can you send me a code sample of the bug?

**Comment by koush** [comment]
Same bug as https://github.com/koush/UrlImageViewHelper/issues/43

**Comment by ericlw** [comment]
I don't know how much a code sample would help since there are so many pieces to putting a listview+adapter in a viewpager, I've fixed the message by commenting out that line in your code. Judging from what I read in Issue #43 it seems like it would be possible for this to happen if I had two identical imageviews being rendered/recycled both in the current listview as well as in an unseen listview in another part of the viewpager.

Does that seem plausible to you?

**Comment by koush** [comment]
Well, I don't see how it is possible, since any time I add something to the "dead" cache, I also remove it from the live cache. Which is why I had that assert there.
I may just remove the assert though, since it is benign, but I suspect it may be masking a larger issue.

**Comment by koush** [comment]
Well, I've commented the assert out, since the assertion is basically benign.
