### ISSUE TITLE
Rotation Bug

### ISSUE THREAD

**Issue by irrelevantat** [koush/UrlImageViewHelper#46]
I am not quite sure if this is an ImageView, JPEG or UrlImageViewHelper specific issue, but I'd like to inform you about the problem. (I have written an stackoverflow question to explore the subject: http://stackoverflow.com/questions/14419449/how-does-the-jpeg-orientation-feature-work)

To summarize the issue: A JPEG image, displayed correctly in a browser, will be displayed differently (rotated by 90°) on Android using the UrlImageViewHelper. The image in the browser loads from left to right. When I load normal images (that are loading from top to bottom in my browser) with the UrlImageViewHelper, they will be displayed perfectly. 

Other Applications (OSX Preview, every Browser and the iOS ImageView) do not have any problems with the image. The only difference is (as mentioned above), that the image will be loaded from right to left.

If you believe, that this is not an UrlImageViewHelper specific problem, please close this issue.

**Comment by koush** [comment]
Try this:

Put the rotated jpeg in your res/drawable. Set an imageview to use that. See what happens.

I would not be surprised if this were an Android bug. UrlImageViewHelper doesn't actually do special image loading. It just uses the BitmapFactory like it should.

**Comment by irrelevantat** [comment]
Same when loading the image directly. Issue can be closed! Thank you! 

Can I buy you a beer for that?
