### ISSUE TITLE
Improvement: No callback when the image fail to load.

### ISSUE THREAD

**Issue by ChristopheVersieux** [koush/UrlImageViewHelper#48]
Hello Koush,

For the need of my project, I had to check if the image was loaded correctly from the url.

Currently, there is no support for that:
"callback An instance of UrlImageViewCallback that is called when the image successfully finishes loading"

I just wanted to know if this is on purpose or if a onFail could be added in the library:

public interface UrlImageViewCallback {
    void onLoaded(ImageView imageView, Drawable loadedDrawable, String url, boolean loadedFromCache);
    void onFail(ImageView imageView, String url);
}

Thank a lot for your work.

**Comment by koush** [comment]
Hi, the onLoaded is still called with null on failure:

See comment:
                        // onLoaded is called with the loader's result (not what is actually used, ie the default drawable). null indicates failure.

``` java
        final Runnable completion = new Runnable() {
            @Override
            public void run() {
                Assert.assertEquals(Looper.myLooper(), Looper.getMainLooper());
                Drawable usableResult = loader.result;
                if (usableResult == null) {
                    usableResult = defaultDrawable;
                    mLiveCache.put(url, usableResult);
                }
                mPendingDownloads.remove(url);
                if (callback != null && imageView == null)
                    callback.onLoaded(null, loader.result, url, false);
                int waitingCount = 0;
                for (final ImageView iv: downloads) {
                    // validate the url it is waiting for
                    final String pendingUrl = mPendingViews.get(iv);
                    if (!url.equals(pendingUrl)) {
                        clog("Ignoring out of date request to update view for " + url + " " + pendingUrl + " " + iv);
                        continue;
                    }
                    waitingCount++;
                    mPendingViews.remove(iv);
                    if (usableResult != null) {
                        iv.setImageDrawable(usableResult);
                        // onLoaded is called with the loader's result (not what is actually used). null indicates failure.
                        if (callback != null && iv == imageView)
                            callback.onLoaded(iv, loader.result, url, false);
                    }
                }
                clog("Populated: " + waitingCount);
            }
        };
```

**Comment by koush** [comment]
Though there seems to be a bug where subsequent calls to the same url will result in the callback being called with the cached default drawable. Is that the issue you are experiencing?

**Comment by ChristopheVersieux** [comment]
Sounds like I am working on an old version, sorry!

```
if (usableResult != null) {
    (...)
    if (callback != null && iv == imageView)
        callback.onLoaded(iv, loader.result, url, false);
} else {
    if (callback != null)
    callback.onFail(imageView, url);
}
```

I think that you can close the issue... :-S

**Comment by koush** [comment]
This should fix the bug, so you know if the drawable was correctly loaded:
https://github.com/koush/UrlImageViewHelper/commit/923ba4242ef170e0f39bfe82f02d398d0c113b5a

The callback will return with "null" for the drawable.

**Comment by koush** [comment]
@ChristopheVersieux I do not want to add an onFail mechanism, as the failure case was already built into onLoaded (drawable is null).

It would also break other apps who would pull from this repository with an update :) I'm hesitant to cause developer pain.

I do like your change, but I think the fix I just checked in would be the path of least resistance.

**Comment by koush** [comment]
I just added some comments on UrlImageViewCallback to better indicate how it works.

**Comment by ChristopheVersieux** [comment]
You should notify when usableResult is null...
(BTW, I understand that onFail is not a good idea)

```
if (usableResult != null) {
    (...)
    if (callback != null && iv == imageView)
        callback.onLoaded(iv, loader.result, url, false);
} else {
    if (callback != null)
    callback.onLoaded(iv, loader.result, url, false);
}
```

**Comment by koush** [comment]
@ChristopheVersieux Ah yes, that's a bug.

Fixed with:
https://github.com/koush/UrlImageViewHelper/commit/50322a6475344c597c7fc63856d6a556d81d066a

**Comment by koush** [comment]
Re: your change

Need to check to see if iv == imageView, because views get recycled in ListView. So, that could erroneously invoke the callback for an ImageView that has changed the url it is loading.

In this scenario, it is actually possible to _not receive a callback at all_ when the view is recycled. To address this, you could first call loadUrlDrawable (with a callback), and then setUrlDrawable. Both loads just get queued into the same request, so you don't need to worry about that being inefficient or that it is making two network calls.

**Comment by ChristopheVersieux** [comment]
Thanks!
