### ISSUE TITLE
Need to know when image is finished downloading, and possible return bitmap/drawable/imageview

### ISSUE THREAD

**Issue by ericlw** [koush/UrlImageViewHelper#49]
Hello, I am using loadUrlDrawable to cache images before hand based on a url. My dilemma is that I want to post process the returned image (blur, specifically) once it is received. But outside of the library I can't tell if the image has been received, I'm not sure where to add something to your library to tell me this, and I'm definitely not sure where to put my JNI blur function. It takes bitmaps.

I've done image downloading myself before, but I really like how this library caches things and uses memory.

Maybe I'll cross-post this on stackoverflow

**Comment by koush** [comment]
Use the callback argument
