### ISSUE TITLE
cleanup method uses the wrong path to the files to be deleted

### ISSUE THREAD

**Issue by oviroa** [koush/UrlImageViewHelper#5]
Hi -

First of all, thanks for a very useful component. Just wanted to point out that your cleanup function does not do what it's supposed to at least on the 2 devices I used, a Nexus 1 and a Galaxy Nexus, both GSM/ATT. It looks like in the delete loop, you are using the plain file string:
File f = new File(file);
where it needs to be something like this: 
File f = new File(context.getFilesDir() + "/"+file )

I needed this to work in order to create a general cache cleanup method so my app can remove cached images when the user changes accounts.

On a different note, have you thought about adding a listener that would notify when images are done loading. I tried it myself but I've been failing because of the multi-thread nature of the class. 

Thanks.
Ovi

**Comment by koush** [comment]
Thanks, fixed the bug. If you want to add listeners, just add them inside the handler.run, and invoke them. All callbacks should call into the main thread. Feel free to send a pull request once implemented.

**Comment by oviroa** [comment]
I actually tried to add them inside the AsyncTask, but in cases where a larger number of images are being loaded (as part of a list for example) the callbacks get messed up. They are not able to differentiate between the images. The callbacks get triggered but they cannot identify which image they are intended for. Hope this makes sense.
