### ISSUE TITLE
from cache returns true and really imagebitmap is null

### ISSUE THREAD

**Issue by FrancescLlao** [koush/UrlImageViewHelper#53]
Hi,
Sorry, my english is not very good. I'm from Catalonia.

I am using your fabulous urlimageviewHelper.
I found a possible error. My activity has a receiver internet changes.

1) I disconnected internet.
2) I open an activity with a list of images.
3) urlimageviewhelper try to download the images but no internet, so it does nothing.
Callback OnLoaded returns:
cache: false, url: http://xxx.com/1360/?width=94&height=74

(It seems that stores a null value in the hash)

4) I connect internet, and when the receiver receives connection, I do adapter.setNotifyDatasetChanged ().

5) Urlimageviewhelper find images in cache, but really not downloaded before and returns a null imageBitmap.
Callback OnLoaded returns:
cache: true, url: http://xxx.com/1360/?width=94&height=74

How I can fix this?
One posible solution is using cacheDurationMs = 0, but it seems not the best solution... (Now i have tried to use cacheDurationMs = 0 and not working...) the problem is urlimageviewhelper returns null images..

THANKS! and GOOD JOB!

**Comment by koush** [comment]
This is expected behavior.

It will cache the null result to prevent the subsequent network call. This is done for a variety of reasons: 404 error, network issues, corrupt bitmap, etc.

If you want to force a null bitmap to always be refreshed, remove it from the cache on the callback I guess.

**Comment by koush** [comment]
Another fix may be for the library to not cache any results if the network is inaccessible.

**Comment by FrancescLlao** [comment]
but... why if i put cacheDuration to 0 ms the problem persists? The normal situation would be redownload the image when i call notifydata... 

Updated: Sorry, if i put 1000 ms then it works! but cache live is very short...

If you want to force a null bitmap to always be refreshed, remove it from the cache on the callback I guess.
How can i do this?

one solution may be create a function to clean specific url, for example:

```
@Override
public void onLoaded(ImageView imageView, Bitmap loadedBitmap, String url, boolean loadedFromCache) {
    if(loadedBitmap == null)
        UrlImageViewHelper.cleanup(context, url); <---- this function does not exists, so what is the best way to implement this function?
}
```

**Comment by FrancescLlao** [comment]
Please, i need your help, i need one function to remove specific url from cache in your library

i have created this function to remove from cache a null file, but file does not exist obviously.

So, what is the array from that i should remove the file??
mDeadCache?
mLiveCache?
mAllCache?

```
public void onLoaded(ImageView imageView, Bitmap loadedBitmap, String url, boolean loadedFromCache) {
    if(loadedBitmap == null){
        UrlImageViewHelper.cleanupUrl(this, UrlImageViewHelper.getFilenameForUrl(url)));    
    }
}

public static boolean cleanupUrl(final Context context, String url) {
    try {
        final String[] files = context.getFilesDir().list();
        if (files == null) {
            return false;
        }
        for (final String file : files) {
            if (!file.equals(url)) {
                continue;
            }
            final File f = new File(context.getFilesDir().getAbsolutePath() + '/' + file);
            f.delete();
            return true;
        }
        return false;
    } catch (final Exception e) {
        e.printStackTrace();
        return false;
    }
}
```

**Comment by koush** [comment]
Added a remove method to remove a single url:
https://github.com/koush/UrlImageViewHelper/commit/e118d948f5c9b9d63edebb152edd2d768aa61804
