### ISSUE TITLE
Same image, multiple sizes, display problems.

### ISSUE THREAD

**Issue by brpaz** [koush/UrlImageViewHelper#59]
Hi. I have a problem. I am not sure if its related to your library or not but I think it is.
I have multiple imageViews in various activities for the same image. What differs are the imageView attributes,  android:layout_width,  android:layout_height,  android:scaleType.

The problem is, when I go to the first activity the image renders correctly. Then I go to the 2nd activity which has other imageVIew with different size for the same image. If I go back to the 1st activity the image size/scale is screwed. Itś like its saving the resized image in the cache and because its the same image, the other imageView doenst use the image in the original size to apply the scale/resize.

I hope I was clear.

**Comment by koush** [comment]
Are you using the latest version of this library?

**Comment by koush** [comment]
ping
