### ISSUE TITLE
Images are awalys in a small size.

### ISSUE THREAD

**Issue by witalobenicio** [koush/UrlImageViewHelper#69]
Is there a way to get the real size of the image? A need to load one image, just on, in the screen, but with the library, it always in a different size (smaller size).

**Comment by koush** [comment]
Turn off the autoresize option

**Comment by witalobenicio** [comment]
ok...how can i do this?

**Comment by AfzalivE** [comment]
I think koush is talking about the setUseBitmapScaling function.

**Comment by koush** [comment]
Right

**Comment by koush** [comment]
https://github.com/koush/UrlImageViewHelper/blob/master/UrlImageViewHelper/src/com/koushikdutta/urlimageviewhelper/UrlImageViewHelper.java#L73

**Comment by witalobenicio** [comment]
I try this. Didnt work. But fine, i code this part, that was only in one fragment.

**Comment by koush** [comment]
You used it like:

``` java
UrlImageViewHelper.setUseBitmapScaling(false);
```

Right?

**Comment by witalobenicio** [comment]
Yep.

**Comment by koush** [comment]
Hm, well, truth be told, I don't use this library anymore, as it has been superseded by ion. I've addressed a lot of the issues (such as this one), as well as a ton of features. And it performs better, has better caching, and also serves as a http client stack, etc.
Switching is fairly painless (I migrated several projects in like 30 minutes).

https://github.com/koush/ion
