### ISSUE TITLE
Image not showing until after scrolling in listview

### ISSUE THREAD

**Issue by jtietema** [koush/UrlImageViewHelper#7]
I'm using the UrlImageViewHelper with a ViewPager with ListFragments and when I enter the screen all ImageViews in the listview are white. They do not hold the placeholder and also do not get updated when the image is received.

When I scroll down the new views appearing at the bottom do show results and placeholders. When I scoll up the also work fine. So it seems everything works fine when the views are reused, but initially they don't work.

**Comment by koush** [comment]
Can you provide sample code of this issue?

**Comment by jtietema** [comment]
Below my getView method of my adapter. It calls the UrlImageViewHelper for every row. The images after scolling are correct. They are not old images from the convertView that get reused.

``` java
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        if (convertView == null) {
            convertView = LayoutInflater.from(context).inflate(R.layout.club_selection_row, null);
        }
        Person person = team.getPersons().get(position);
        TextView name = (TextView) convertView.findViewById(R.id.person_name);
        name.setText(person.getName());
        ImageView playerImage = (ImageView) convertView.findViewById(R.id.player_image);
        String url = String.format(Settings.Urls.URL_PLAYER_PHOTO, person.getId());
        UrlImageViewHelper.setUrlDrawable(playerImage, url, R.drawable.placeholder_image , UrlImageViewHelper.CACHE_DURATION_ONE_DAY);

        return convertView;
    }
```

**Comment by jtietema** [comment]
Found the problem, it's in a custom View we use and not a problem in UrlImageViewHelper. Sorry to bother you with this :-/ Thumbs up for UrlImageViewHelper though, we use it all over our project, so a big "thank you" for that :-)

**Comment by koush** [comment]
Great to hear that. I was assuming it was something like that. I use/reuse imageviews in listviews quite a bit, and had never seen that problem :)
