### ISSUE TITLE
coffee feature broken

### ISSUE THREAD

**Issue by TeknoloGenie** [koush/UrlImageViewHelper#70]
-------  "Android library that sets an ImageView's contents from a url. Manages image downloading, caching, and makes your coffee too." --------- 

I woke up this morning, and my coffee pot was empty, came over here to check and see if there were any open/closed issues that would maybe help me and there weren't any. Im not sure if anyone else is having this issue or not. Hopefully someone can fix this soon...really love coffee... Great project guys, keep up the great work.

------ (funny issue, not to be taken seriously) lol

**Comment by koush** [comment]
:)

**Comment by koush** [comment]
Check out ion. It everything UlrImageViewHelper does and more, and better/faster. No coffee yet though.

https://github.com/koush/ion

**Comment by TeknoloGenie** [comment]
@koush wow thanks, very useful to know. I never would of though that it gets better. Great work. Too bad about the coffee lol. 

Also i REALLY love what you did with the loading if images, with
.animateLoad(spinAnimation)
.animateIn(fadeInAnimation)

Were about 2 days away from launching our app into google play and im debating on if i should pull an all nighter to make the switch from my old loopj frameworks to yours, you wouldnt happen to make things easier on me and have a comparison chart between the two would you?

**Comment by TeknoloGenie** [comment]
You know what.. i read down about 10 more lines and seen how Ion did the following two things for me... its settled. I'll be up all night making that switch... now its REALLY too bad that coffee maker doesnt work yet.. oh well, better start brewing my own. Thanks @koush , as soon as i can i'll start making my share of contributions. Thanks again.
