### ISSUE TITLE
no class def found error UrlImageViewHelper

### ISSUE THREAD

**Issue by ghost** [koush/UrlImageViewHelper#78]
Hi,
i have downloaded jar file manually and added to my project.

The project read library, not receive error when i import library in activity but when project run i receive:

java.lang.NoClassDefFoundError: com.koushikdutta.urlimageviewhelper.UrlImageViewHelper

Help me pls!

**Comment by ghost** [comment]
up

**Comment by koush** [comment]
you using proguard? Not sure why this would happen.
