### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by suarezjulian** [koush/UrlImageViewHelper#9]
First off thanks for the great library it has saved my day a lot of times!!!

I'm using your library to populate items on a listview which contains all of the users facebook friends, and I have to show the friend's photo.

I'm using the simplest form of the library like this:
UrlImageViewHelper.setUrlDrawable(iv, url);

It has happened only a handful of times that I get the exception below. I was wondering if there is any configuration I can change to solve this issue.

E/AndroidRuntime(21066): FATAL EXCEPTION: main
E/AndroidRuntime(21066): java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@423b40f8 rejected from java.util.concurrent.ThreadPoolExecutor@41989790[Running, pool size = 128, active threads = 128, queued tasks = 9, completed tasks = 54]
E/AndroidRuntime(21066): at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1967)
E/AndroidRuntime(21066): at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:782)
E/AndroidRuntime(21066): at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1303)
E/AndroidRuntime(21066): at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:564)
E/AndroidRuntime(21066): at com.samsung.samsungolympics.util.urlimageviewhelper.UrlImageViewHelper.setUrlDrawable(UrlImageViewHelper.java:316)
E/AndroidRuntime(21066): at com.samsung.samsungolympics.util.urlimageviewhelper.UrlImageViewHelper.setUrlDrawable(UrlImageViewHelper.java:82)
E/AndroidRuntime(21066): at com.samsung.samsungolympics.register.AdapterOrderedByLetter.bindView(AdapterOrderedByLetter.java:153)
E/AndroidRuntime(21066): at com.samsung.samsungolympics.register.AdapterOrderedByLetter.getView(AdapterOrderedByLetter.java:137)
E/AndroidRuntime(21066): at android.widget.AbsListView.obtainView(AbsListView.java:2195)
E/AndroidRuntime(21066): at android.widget.ListView.makeAndAddView(ListView.java:1774)
E/AndroidRuntime(21066): at android.widget.ListView.fillDown(ListView.java:672)
E/AndroidRuntime(21066): at android.widget.ListView.fillGap(ListView.java:636)
E/AndroidRuntime(21066): at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5257)
E/AndroidRuntime(21066): at android.widget.AbsListView$TwFlingRunnable.run(AbsListView.java:4150)
E/AndroidRuntime(21066): at android.os.Handler.handleCallback(Handler.java:605)
E/AndroidRuntime(21066): at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(21066): at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(21066): at android.app.ActivityThread.main(ActivityThread.java:4512)
E/AndroidRuntime(21066): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(21066): at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(21066): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
E/AndroidRuntime(21066): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
E/AndroidRuntime(21066): at dalvik.system.NativeStart.main(Native Method)

**Comment by koush** [comment]
Looks like you're trying to execute too many threads maybe? I've never seen that before. Are you loading hundreds of images at once?

**Comment by suarezjulian** [comment]
Hi koush, yes I'm loading quite a lot of pictures (FB friends profile photos), but actually the issue was only partially related to your library. The thing is that on Android 4+ the default behavior for AsyncTask is to be serialized , that is, that only one Asynctask is executed at a time, and if there are more than one task pending it will go to a queue. Check this link http://commonsware.com/blog/2012/04/20/asynctask-threading-regression-confirmed.html to get an explanation of this.

So the thing was that I added a modification to your library that I forgot, in order to force the execution of multiple tasks on parallel, an that was causing the issue.

**Comment by koush** [comment]
Cool, thanks, I'll switch off of using AsyncTask probably.
